global:
  scrape_interval: 15s  # Frequency of metric scraping

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'metrics'
    static_configs:
      - targets: ['metrics:8000'] 
